"""add_is_manager_admin

Revision ID: 6c6b45ffe090
Revises: 42065519a495
Create Date: 2026-02-18 08:22:57.322525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c6b45ffe090"
down_revision: Union[str, None] = "42065519a495"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_chat_user",
        sa.Column(
            "is_manager_admin", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.execute("UPDATE telegram_chat_user SET is_manager_admin = is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_chat_user", "is_manager_admin")
    # ### end Alembic commands ###
